# Generated by Django 3.2.16 on 2023-01-13 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('bike_slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '2. Bikes',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Catelogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('part_slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('part_number', models.CharField(max_length=255)),
                ('item_Description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='product_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catlogue_added_by', to=settings.AUTH_USER_MODEL)),
                ('part_for_bike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bike', to='store.bikes')),
            ],
            options={
                'verbose_name_plural': '5. Catelogue',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('company_slug', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': '1. Companies',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('file', models.FileField(upload_to='invoices/')),
            ],
            options={
                'verbose_name_plural': '6. Invoice',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('manufacturer_slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '3. Manufacturer',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(help_text='supplier Name', max_length=255)),
                ('supplier_slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('account_no', models.CharField(max_length=255, null=True)),
                ('pan_no', models.CharField(max_length=255, null=True)),
                ('gst_no', models.CharField(max_length=255, null=True)),
                ('cin_no', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('0', 'INACTIVE'), ('1', 'ACTIVE')], default='1', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('manufacturer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='store.manufacturer')),
            ],
            options={
                'verbose_name_plural': '4. Supplier',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('Quantity', models.IntegerField(default='0')),
                ('max_discount', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('status', models.CharField(choices=[('0', 'Available'), ('1', 'Not Available')], default='0', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_added_by', to=settings.AUTH_USER_MODEL)),
                ('invoice_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='store.invoice')),
                ('part_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catlogue_part_name', to='store.catelogue')),
                ('part_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catlogue_part_number', to='store.catelogue')),
                ('photo_display', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_photo', to='store.catelogue')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier')),
            ],
            options={
                'verbose_name_plural': '7. Products',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='catelogue',
            name='part_manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_manufacturer', to='store.manufacturer'),
        ),
        migrations.AddField(
            model_name='catelogue',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='store.company'),
        ),
    ]
