# Generated by Django 3.2.16 on 2023-01-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230113_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_display',
        ),
    ]
