# Generated by Django 3.2.16 on 2023-01-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='Address',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
