# Generated by Django 3.2.16 on 2023-01-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userbase_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='about',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='country',
        ),
    ]
